DROP TABLE IF EXISTS meal_plan_recipe;
DROP TABLE IF EXISTS meal_plan;
DROP TABLE IF EXISTS recipe_ingredient;
DROP TABLE IF EXISTS products;
DROP TABLE IF EXISTS recipes;
DROP TABLE IF EXISTS users;
